STATUS_UPDATE_START_DELAY: int = 1 * 60
STATUS_UPDATE_DELAY: int = 10 * 60

AUTO_DELETE_COMMANDS: bool = True
AUTO_DELETE_MESSAGES: bool = True
MESSAGE_LIFETIME: int = 60

CONNECTION_RETRY_DEALY: int = 60
MESSAGE_SIZE_LIMIT: int = 2048
