name: Deploy

on:
  workflow_run:
    workflows: [Build docker]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to server
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}

          SERVER_DIR: ${{ vars.SERVER_DIR }}

        run: |
          echo "$KEY" > ssh_key
          chmod 600 ssh_key

          ssh -i ssh_key \
            -p $PORT \
            -o StrictHostKeyChecking=no \
            $USER@$HOST \
            "
              mkdir -p $SERVER_DIR
              cd $SERVER_DIR

              curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml \
                -o docker-compose.yml

              docker compose pull && docker compose up -d
            "

          rm ssh_key
